# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_vector.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_vector.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12image_vector.proto\"&\n\x0bImageVector\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vec\x18\x02 \x01(\x0c\x62\x06proto3'
)


_IMAGEVECTOR = _descriptor.Descriptor(
  name='ImageVector',
  full_name='ImageVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ImageVector.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vec', full_name='ImageVector.vec', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['ImageVector'] = _IMAGEVECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageVector = _reflection.GeneratedProtocolMessageType('ImageVector', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEVECTOR,
  '__module__' : 'image_vector_pb2'
  # @@protoc_insertion_point(class_scope:ImageVector)
  })
_sym_db.RegisterMessage(ImageVector)


# @@protoc_insertion_point(module_scope)
