# Generated by Django 3.0.5 on 2020-04-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_temp'),
        ),
    ]
