# Generated by Django 3.0.5 on 2020-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_app', '0002_auto_20200404_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='MEDIA_ROOT')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
