# Generated by Django 3.0.5 on 2020-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_app', '0003_auto_20200405_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
