# Generated by Django 3.0.5 on 2020-04-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_app', '0004_auto_20200408_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_images_list', models.TextField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_app.UploadedImage')),
            ],
        ),
    ]
