# Generated by Django 3.0.5 on 2020-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_app', '0005_similarimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='similar_images_list',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='SimilarImages',
        ),
    ]
