# Generated by Django 3.0.5 on 2020-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_app', '0006_auto_20200409_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='similar_images_list',
            field=models.CharField(default='{}', max_length=1000),
        ),
    ]
