# Generated by Django 3.0.5 on 2020-04-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_app', '0007_auto_20200409_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_URL/uploaded'),
        ),
    ]
