# Generated by Django 3.0.5 on 2020-04-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_app', '0008_auto_20200410_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded'),
        ),
    ]
