# Generated by Django 3.0.5 on 2020-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(blank=True, null=True, upload_to='uploaded/')),
                ('similar_images_list', models.CharField(default='{}', max_length=1000)),
            ],
        ),
    ]
