# Generated by Django 3.0.5 on 2020-04-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_plagiarism', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='imageURL',
            new_name='image',
        ),
    ]
