# Generated by Django 3.0.5 on 2020-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_plagiarism', '0002_auto_20200410_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='images_probability_list',
            field=models.CharField(default='{}', max_length=1000),
        ),
    ]
