# Generated by Django 3.0.5 on 2020-04-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_plagiarism', '0003_uploadedimage_images_probability_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='images_probability_list',
            new_name='probability_list',
        ),
    ]
